version: '3.7'

services:
  server:
    image: atlassian/bamboo-server:6.8.1
    init: true
    restart: "unless-stopped"
    volumes:
    - server:/var/atlassian/application-data/bamboo
    networks:
    - bamboo
    ports:
    - 54663:54663
    - 8085:8085

volumes:
  agent:
  server:
networks:
  bamboo: